name: GitHub Actions Demo
run-name: test run
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The secret is ${{ secrets.GITHUB_TOKEN }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
